[package]
name = "cortex"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["staticlib"]
path = "src/lib.rs"

[dependencies]
zeroize = { version = "1", default-features = false }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
