services:
  blindnet-idf-rust:
    image: espressif/idf-rust:esp32_latest
    container_name: blindnet-idf-rust
    working_dir: /workspace/BlindNet
    stdin_open: true
    tty: true
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    volumes:
      - .:/workspace/BlindNet
      - blindnet-cargo-registry:/root/.cargo/registry
      - blindnet-cargo-git:/root/.cargo/git
      - blindnet-espressif-cache:/root/.espressif

volumes:
  blindnet-cargo-registry:
  blindnet-cargo-git:
  blindnet-espressif-cache:
