pub type EspErr = i32;

pub const ESP_OK: EspErr = 0;
pub const ESP_FAIL: EspErr = -1;
pub const ESP_ERR_NO_MEM: EspErr = 0x101;
pub const ESP_ERR_INVALID_ARG: EspErr = 0x102;
pub const ESP_ERR_INVALID_STATE: EspErr = 0x103;
pub const ESP_ERR_INVALID_SIZE: EspErr = 0x104;
pub const ESP_ERR_NOT_FOUND: EspErr = 0x105;
pub const ESP_ERR_NOT_SUPPORTED: EspErr = 0x106;
pub const ESP_ERR_TIMEOUT: EspErr = 0x107;
pub const ESP_ERR_INVALID_RESPONSE: EspErr = 0x108;
pub const ESP_ERR_INVALID_CRC: EspErr = 0x109;
pub const ESP_ERR_INVALID_VERSION: EspErr = 0x10A;
pub const ESP_ERR_INVALID_MAC: EspErr = 0x10B;

pub mod active_enzyme;
pub mod active_substance;
pub mod admin_server;
pub mod amino_acids;
pub mod capsule_pill;
pub mod config_store;
pub mod device_registry;
pub mod dns_filter;
pub mod event_bus;
pub mod flow_table;
pub mod g2g_ble;
pub mod mqtt_broker;
pub mod policy_engine;
pub mod quarantine_manager;
pub mod rate_limiter;
pub mod ribosome_store;
pub mod ribosome_table;
pub mod rna_membrane;
pub mod setup_ap;
pub mod setup_button;
pub mod stomach_cp_cache;
pub mod swarm_agent;
pub mod telemetry_agent;
pub mod wifi_manager;
pub mod zone_firewall;
pub mod zone_gateway;
