name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build
        run: cargo build --workspace --all-targets

      - name: Format check
        run: cargo fmt -- --check

      - name: Lint
        run: cargo clippy --workspace -- -D warnings

      - name: Test
        run: cargo test --workspace
